apps/login/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login$', views.login, name='login'),
    url(r'^register$', views.register, name='register'),
]

user_dashboard/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.login.urls', namespace='login')),
    url(r'^users/', include('apps.dashboard.urls', namespace='dashboard')),
]

apps/login/models.py
from __future__ import unicode_literals
from django.db import models
from re import match, search
from bcrypt import hashpw, gensalt

class UserManager(models.Manager):
    # REGISTER form - login/index
    def register(self, email, first_name, last_name, password, confirm_password, csrfmiddlewaretoken):
        messagelist = []
        # Validate email
        email = email[0]
        if not match(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$', email):
            messagelist.append("Invalid email address")
        elif self.filter(email=email):
            messagelist.append("Email Address already in use")
        # Validate first_name
        first_name = first_name[0]
        if len(first_name) < 2:
            messagelist.append("First Name must be at least 2 characters long")
        elif search(r'[^a-zA-Z]', first_name):
            messagelist.append("First Name must only contain letters")
        # Validate last_name
        last_name = last_name[0]
        if len(last_name) < 2:
            messagelist.append("Last Name must be at least 2 characters long")
        elif search(r'[^a-zA-Z]', last_name):
            messagelist.append("Last Name must only contain letters")
        # Validate password
        password = password[0]
        if len(password) < 8:
            messagelist.append("Password must be at least 8 characters long")
        # Validate conf_password
        conf_password = confirm_password[0]
        if conf_password != password:
            messagelist.append("Password does not match")
        # Check if all validation checks passed
        if len(messagelist) > 0:
            return (False, messagelist)
        pw_hash = hashpw(password.encode(), gensalt())
        new_user = self.create(email=email, first_name=first_name, last_name=last_name, password=pw_hash)
        # Make first registered user an admin
        if new_user.id == 1:
            new_user.update(user_level='admin')
        return (True, new_user.id)
    # LOGIN form - login/index
    def login(self, email, password):
        if self.filter(email=email):
            user = self.get(email=email)
            if hashpw(password.encode(), user.password.encode()) == user.password:
                return (True, user.id)
            else:
                return (False, "Invalid password")
        else:
            return (False, "Invalid email address")
    # EDIT INFO form - dashboard/edit/user_id
    def editInfo(self, user_id, email, first_name, last_name, csrfmiddlewaretoken, user_level=['user']):
        messagelist = []
        # Validate email
        email = email[0]
        if not match(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$', email):
            messagelist.append("Invalid email address")
        # Validate first_name
        first_name = first_name[0]
        if len(first_name) < 2:
            messagelist.append("First Name must be at least 2 characters long")
        elif search(r'[^a-zA-Z]', first_name):
            messagelist.append("First Name must only contain letters")
        # Validate last_name
        last_name = last_name[0]
        if len(last_name) < 2:
            messagelist.append("Last Name must be at least 2 characters long")
        elif search(r'[^a-zA-Z]', last_name):
            messagelist.append("Last Name must only contain letters")
        # Validate user_level
        user_level = user_level[0]
        if user_level != 'user' and user_level != 'admin':
            messagelist.append("User Level must be 'user' or 'admin'")
        # Check if all validations passed
        if len(messagelist) > 0:
            return (False, messagelist)
        self.filter(id=user_id).update(email=email, first_name=first_name, last_name=last_name, user_level=user_level)
        return (True, "User Info updated successfully")
    # CHANGE PASSWORD form - dashboard/edit/user_id
    def editPassword(self, user_id, password, confirm_password, csrfmiddlewaretoken):
        messagelist = []
        # Validate password
        password = password[0]
        if len(password) < 8:
            messagelist.append("Password must be at least 8 characters long")
        # Validate conf_password
        conf_password = confirm_password[0]
        if conf_password != password:
            messagelist.append("Password does not match")
        # Check if all validation checks passed
        if len(messagelist) > 0:
            return(False, messagelist)
        pw_hash = hashpw(password.encode(), gensalt())
        self.filter(id=user_id).update(password=pw_hash)
        return (True, "User Info updated successfully")
    # EDIT DESCRIPTION form - dashboard/edit/user_id
    def editDescription(self, user_id, description):
        # Validate description
        if len(description) == 0:
            description = ""
        self.filter(id=user_id).update(description=str(description))
        return (True, "Description Successfully Updated")

class User(models.Model):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    password = models.CharField(max_length=255)
    user_level = models.CharField(
        max_length=5,
        choices=(('user', 'User'), ('admin', 'Admin')),
        default='user')
    description = models.TextField(max_length=400, default='')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    userManager = UserManager()
    objects = models.Manager()

apps/login/forms.py
from django import forms
from .models import User

class LoginForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'placeholder': 'Email'
        }))
    password = forms.CharField(max_length=45, widget=forms.PasswordInput(attrs={
            'class':'form-control',
            'placeholder': 'Password'
        }))

class RegisterForm(forms.Form):
    email = forms.EmailField()
    first_name = forms.CharField(max_length=45)
    last_name = forms.CharField(max_length=45)
    password = forms.CharField(max_length=45, widget=forms.PasswordInput)
    confirm_password = forms.CharField(max_length=45, widget=forms.PasswordInput)

apps/login/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from .models import User
from .forms import RegisterForm, LoginForm

# Login and reg at homepage
def index(request):
    request.session.clear()
    context = {
        'regform': RegisterForm,
        'loginform': LoginForm
    }
    return render(request, 'login/index.html', context)

# Submit registration form
def register(request):
    regstatus = User.userManager.register(**request.POST)
    if regstatus[0]:
        request.session['user_id'] = regstatus[1]
        return redirect(reverse('dashboard:index'))
    else:
        for message in regstatus[1]:
            messages.warning(request, message)
        return redirect(reverse('login:index'))

# Submit login form
def login(request):
    loginstatus = User.userManager.login(request.POST['email'], request.POST['password'])
    if loginstatus[0]:
        request.session['user_id'] = loginstatus[1]
        return redirect(reverse('dashboard:index'))
    else:
        messages.warning(request, loginstatus[1])
        return redirect(reverse('login:index'))

apps/login/templates/login/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Welcome | User Dashboard</title>
    {% load staticfiles %}
    <!-- Latest compiled and minified CSS -->
    <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" rel="stylesheet">
    <!-- Optional theme -->
    <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'login/css/style.css' %}">
    <!-- Latest compiled and minified JavaScript -->
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand">USER DASHBOARD</a>
            </div>
            <form class="form-inline navbar-right" action="{% url 'login:login' %}" method="post">
                {% csrf_token %}
                {% for input in loginform %}
                    <div class="form-group">
                        {{ input }}
                    </div>
                {% endfor %}
                <button class="btn btn-default btn-sm" type="submit">Log In</button>
            </form>
        </div>
    </nav> <!-- end navbar -->
    <div class='container'>
        <h2>Welcome to the User Dashboard!</h2>
        <div class="row">
            <div class="col-md-6">
                <h4>The User Dashboard allows you to stay connected with other members in the community. Sign up now to receive and share the most up-to-date news!</h4>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <span class="glyphicon glyphicon-tint" aria-hidden="true"></span>
                <h3> Create </h3>
            </div>
            <div class="col-md-3">
                <span class="glyphicon glyphicon-cloud" aria-hidden="true"></span>
                <h3> Retrieve </h3>
            </div>
            <div class="col-md-3">
                <span class="glyphicon glyphicon-leaf" aria-hidden="true"></span>
                <h3> Update </h3>
            </div>
            <div class="col-md-3">
                <span class="glyphicon glyphicon-fire" aria-hidden="true"></span>
                <h3> Delete </h3>
            </div>
        </div> <!-- end CRUD icon row -->
        {% if messages %}
            <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
            </ul>
        {% endif %}  <!-- end messages -->
        <div class="register_space">
            <h4>New User? Register Below!</h4>
            <form action="{% url 'login:register' %}" method="post">
            {% csrf_token %}
                <table class="table_space">
                {{ regform.as_table }}
                </table>
                <button class='btn btn-success btn-md' type='submit'>Register</button>
            </form>
        </div> <!-- end register form -->
    </div>
</body>
</html>