apps/dashboard/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^edit/(?P<user_id>\d+)$', views.edit, name='edit'),
    url(r'^edit_pw/(?P<user_id>\d+)$', views.edit_pw, name='edit_pw'),  #POST
    url(r'^edit_desc/(?P<user_id>\d+)$', views.edit_desc, name='edit_desc'),  #POST
    url(r'^edit_info/(?P<user_id>\d+)$', views.edit_info, name='edit_info'),  #POST
    url(r'^remove/(?P<user_id>\d+)$', views.remove_admin, name='remove_admin'),  #POST
    url(r'^new$', views.new_admin, name='new_admin'),
    url(r'^create$', views.create_admin, name='create_admin'),  #POST
    url(r'^show/(?P<user_id>\d+)$', views.show, name='show'),
    url(r'^show/(?P<user_id>\d+)/new$', views.new_message, name="new_message"),  #POST
    url(r'^show/(?P<user_id>\d+)/(?P<message_id>\d+)/new$', views.new_comment, name="new_comment"),  #POST
]

user_dashboard/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.login.urls', namespace='login')),
    url(r'^users/', include('apps.dashboard.urls', namespace='dashboard')),
]

apps/dashboard/models.py
from __future__ import unicode_literals
from django.db import models
from ..login.models import User

# Create your models here.
class Message(models.Model):
	message = models.CharField(max_length=1000)
	walluser = models.ForeignKey(User, related_name='userwall')
	messageuser = models.ForeignKey(User, related_name='usermessage')
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)

class Comment(models.Model):
	comment = models.CharField(max_length=1000)
	user = models.ForeignKey(User, related_name='usercomment')
	message = models.ForeignKey(Message, related_name='messagecomment')
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)

apps/dashboard/forms.py
from django import forms
from .models import User
from ..login.forms import RegisterForm

class EditForm(forms.Form):
	email = forms.EmailField()
	first_name = forms.CharField(max_length=45)
	last_name = forms.CharField(max_length=45)

	def __init__(self, **kwargs):
		user = kwargs.pop('user', None)
		super(EditForm, self).__init__()
		if user:
			self.fields['email'].initial = user.email
			self.fields['first_name'].initial = user.first_name
			self.fields['last_name'].initial = user.last_name

class EditAdminForm(forms.Form):
	email = forms.EmailField()
	first_name = forms.CharField(max_length=45)
	last_name = forms.CharField(max_length=45)
	user_level = forms.ChoiceField([('admin', 'admin'), ('user', 'user')])

	def __init__(self, **kwargs):
		user = kwargs.pop('user', None)
		super(EditAdminForm, self).__init__()
		if user:
			self.fields['email'].initial = user.email
			self.fields['first_name'].initial = user.first_name
			self.fields['last_name'].initial = user.last_name
			self.fields['user_level'].initial = user.user_level

class EditPasswordForm(forms.Form):
	password = forms.CharField(max_length=45, widget=forms.PasswordInput)
	confirm_password = forms.CharField(max_length=45, widget=forms.PasswordInput)

class EditDescriptionForm(forms.Form):
	description = forms.CharField(max_length=255, widget=forms.Textarea, label='')

	def __init__(self, **kwargs):
		user = kwargs.pop('user', None)
		super(EditDescriptionForm, self).__init__()
		if user:
			self.fields['description'].initial = user.description

apps/dashboard/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.core.urlresolvers import reverse
from django.contrib import messages
from .models import User, Message, Comment
from .forms import RegisterForm, EditForm, EditAdminForm, EditPasswordForm, EditDescriptionForm

# user/admin home page
def index(request):
    if not 'user_id' in request.session:
        return redirect(reverse('login:index'))
    current_user = User.objects.get(id=request.session['user_id'])
    user = User.objects.all()
    context = { 'users': user }
    if current_user.user_level == 'admin':
        return render(request, 'dashboard/index_admin.html', context)
    else:
        return render(request, 'dashboard/index.html', context)

# edit page for users and admin
def edit(request, user_id):
    if not 'user_id' in request.session:
        return redirect(reverse('login:index'))
    user = User.objects.get(id=request.session['user_id'])
    # redirect user accessing other user pages
    if user.id != int(user_id) and user.user_level == 'user':
        return redirect(reverse('dashboard:edit', args=[user.id]))
    urlUser = User.objects.get(id=user_id)
    # generate edit forms based on user_level and whose page an admin is looking at
    editForm = EditForm(user=user) if user.user_level == 'user' else EditAdminForm(user=urlUser)
    editDescription = EditDescriptionForm(user=user) if user.id == int(user_id) else ''
    context = {
        'user': urlUser,
        'editForm': editForm,
        'editDescriptionForm': editDescription,
        'editPasswordForm': EditPasswordForm(),
    }
    return render(request, 'dashboard/edit.html', context)

# POST request for user editing info
def edit_info(request, user_id):
    editstatus = User.userManager.editInfo(user_id, **request.POST)
    # generate messages based on whether or not validation was successful
    if editstatus[0]:
        messages.success(request, editstatus[1])
    else:
        for message in editstatus[1]:
            messages.warning(request, message)
    return redirect(reverse('dashboard:edit', args=[user_id]))

# POST request for user editing password
def edit_pw(request, user_id):
    editstatus = User.userManager.editPassword(user_id, **request.POST)
    # generate messages based on whether or not validation was successful
    if editstatus[0]:
        messages.success(request, editstatus[1])
    else:
        for message in editstatus[1]:
            messages.warning(request, message)
    return redirect(reverse('dashboard:edit', args=[user_id]))

# POST request for user editing description
def edit_desc(request, user_id):
    editstatus = User.userManager.editDescription(user_id, request.POST['description'])
    # generate messages based on whether or not validation was successful
    if editstatus[0]:
        messages.success(request, editstatus[1])
    else:
        for message in editstatus[1]:
            messages.warning(request, message)
    return redirect(reverse('dashboard:edit', args=[user_id]))

# POST link for delete user link (admin only)
def remove_admin(request, user_id):
    User.objects.get(id=user_id).delete()
    return redirect(reverse('dashboard:index'))

# admin page to create new user
def new_admin(request):
    if not 'user_id' in request.session:
        return redirect(reverse('login:index'))
    if User.objects.get(id=request.session['user_id']).user_level == 'admin':
        context = {'regform': RegisterForm() }
        return render(request, 'dashboard/new_admin.html', context)
    else:
        return redirect(reverse('dashboard:index'))

# POST link for new user form (admin only)
def create_admin(request):
    create_status = User.userManager.register(**request.POST)
    if create_status[0]:
        return redirect(reverse('dashboard:index'))
    else:
        for message in create_status[1]:
            messages.warning(request, message)
        return redirect(reverse('login:new_admin'))

# show user wall
def show(request, user_id):
    if not 'user_id' in request.session:
        return redirect(reverse('login:index'))
    messages = Message.objects.filter(walluser=user_id).order_by('-id')
    comments = Comment.objects.all()
    user = User.objects.get(id=user_id)
    context = {
        'user': user,
        'messages': messages,
        'comments': comments
    }
    return render(request, 'dashboard/show.html', context)
# POST request for adding message
def new_message(request, user_id):
    messageuser = User.objects.get(id=request.session['user_id'])
    walluser = User.objects.get(id=user_id)
    message = request.POST['message']
    Message.objects.create(messageuser=messageuser, walluser=walluser, message=message)
    return redirect(reverse('dashboard:show', args=user_id))

# POST request for adding comment
def new_comment(request, user_id, message_id):
    user = User.objects.get(id=request.session['user_id'])
    message = Message.objects.get(id=message_id)
    comment = request.POST['comment']
    Comment.objects.create(user=user, message=message, comment=comment)
    return redirect(reverse('dashboard:show', args=user_id))

apps/dashboard/templates/dashboard/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Edit User | User Dashboard</title>
    {% load staticfiles %}
    <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" rel="stylesheet">
    <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/css/style.css' %}">
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'dashboard:index' %}">USER DASHBOARD</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{% url 'dashboard:show' request.session.user_id %}">
                        PROFILE <span class="sr-only">(current)</span></a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'login:index' %}">LOGOFF</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav> <!-- end navbar -->
    <div class='container'>
        {% if user.id == request.session.user_id %}
    		<h3>Edit Profile</h3>
        {% else %}
            <h3>Edit {{ user.first_name }} {{ user.last_name }}</h3>
        {% endif %}
        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}  <!-- end messages -->
        <div class="row">
    		<div class="col-md-6 form" id="editInfoForm">
    		<h4>Edit Information</h4>
    			<form action="{% url 'dashboard:edit_info' user.id %}" method="POST">
    				{% csrf_token %}
                    <table>
    				{{editForm.as_table}}
                    </table>
    				<button type='submit' class='btn btn-success btn-sm'>Save</button>
    			</form>
    		</div> <!-- end Edit Info form -->
    		<div class="col-md-6 form" id="editPasswordForm">
    		<h4>Change Password</h4>
    			<form action="{% url 'dashboard:edit_pw' user.id %}" method="POST">
    				{% csrf_token %}
                    <table>
    				{{editPasswordForm.as_table}}
                    </table>
    				<button type='submit' class='btn btn-success btn-sm'>Update Password</button>
    			</form>
    		</div> <!-- end Change Password form -->
        </div>
        {% if editDescriptionForm %}
        <div class="row">
    		<div class="col-md-6 form" id="editDescritionForm">
    		<h4>Edit Description</h4>
    			<form action="{% url 'dashboard:edit_desc' user.id %}" method="POST">
    				{% csrf_token %}
                    <table>
    				{{editDescriptionForm.as_table}}
                    </table>
    				<button type='submit' class='btn btn-success btn-sm'>Save</button>
    			</form>
    		</div> <!-- end Edit Description form -->
        </div>
        {% endif %}
	</div>
</body>
</html>

apps/dashboard/templates/dashboard/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Home | User Dashboard</title>
    {% load staticfiles %}
    <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" rel="stylesheet">
    <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/css/style.css' %}">
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'dashboard:index' %}">USER DASHBOARD</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{% url 'dashboard:show' request.session.user_id %}">
                        PROFILE <span class="sr-only">(current)</span></a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'login:index' %}">LOGOFF</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav> <!-- end navbar -->
    <div class='container'>
        <h3>All Users</h3>
        <table class="table table-bordered table-hover table-responsive ">
            <tr class="success">
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Created_at</th>
                <th>User_level</th>
            </tr>
            {% for user in users %}
            <tr>
                <td>{{user.id}}</td>
                <td><a href="{%url 'dashboard:show' user.id%}">{{user.first_name}} {{user.last_name}}</a></td>
                <td>{{user.email}}</td>
                <td>{{user.created_at}}</td>
                <td>{{user.user_level}}</td>
            </tr>
            {% endfor %}
        </table> <!-- end user table -->
    </div><!-- end of container -->
</body>
</html>

apps/dashboard/templates/dashboard/index_admin.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Admin Home | User Dashboard</title>
    {% load staticfiles %}
    <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" rel="stylesheet">
    <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/css/style.css' %}">
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header active">
                <a class="navbar-brand" href="{% url 'dashboard:index' %}">USER DASHBOARD</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'dashboard:show' request.session.user_id %}">
                        PROFILE <span class="sr-only">(current)</span></a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'login:index' %}">LOGOFF</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav> <!-- end navbar -->
    <div class='container'>
        <h3 class='less_margin'>Manage Users</h3>
        <table class="table table-bordered table-hover table-responsive">
            <tr class="success">
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Created_at</th>
                <th>User_level</th>
                <th>Actions</th>
            </tr>
            {% for user in users %}
            <tr>
                <td>{{user.id}}</td>
                <td><a href="{%url 'dashboard:show' user.id%}">{{user.first_name}} {{user.last_name}}</a></td>
                <td>{{user.email}}</td>
                <td>{{user.created_at}}</td>
                <td>{{user.user_level}}</td>
                <td>
                    <a href= "{% url 'dashboard:remove_admin' user.id %}">Delete</a>  |
                    <a href="{% url 'dashboard:edit' user.id %}">Edit</a>
                </td>
            </tr>
            {% endfor %}
        </table> <!-- end user table -->
        <div class='button_add'>
            <form action="{% url 'dashboard:new_admin' %}">
                {% csrf_token %}
                <button class='btn btn-success btn-md' type='submit'>Add New</button>
            </form>
        </div>
    </div> <!-- end of container -->
</body>
</html>

apps/dashboard/templates/dashboard/new_admin.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>New User | User Dashboard</title>
    {% load staticfiles %}
    <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" rel="stylesheet">
    <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/css/style.css' %}">
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'dashboard:index' %}">USER DASHBOARD</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'dashboard:show' request.session.user_id %}">
                        PROFILE <span class="sr-only">(current)</span></a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'login:index' %}">LOGOFF</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav> <!-- end navbar -->
    <div class='container'>
        <h3>Add a New User</h3>
        {% if messages %}
            <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
            </ul>
        {% endif %} <!-- end messages -->
        <div class="row">
            <div class="col-md-6 form">
                <form action="{% url 'dashboard:create_admin' %}" method="post">
                    {% csrf_token %}
                    <table>
                    {{ regform.as_table }}
                    </table>
                    <button class='btn btn-success btn-md' type='submit'>Create New User!</button>
                </form>
            </div>
        </div>
    </div> <!-- end container -->
</body>
</html>

apps/dashboard/templates/dashboard/show.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>User Wall | User Dashboard</title>
    {% load staticfiles %}
    <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" rel="stylesheet">
    <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/css/style.css' %}">
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'dashboard:index' %}">USER DASHBOARD</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{% url 'dashboard:show' request.session.user_id %}">
                        PROFILE <span class="sr-only">(current)</span></a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'login:index' %}">LOGOFF</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav> <!-- end navbar -->
    <div class='container'>
        <div class='row'>
            <div class="col-md-6">
                <h3>{{user.first_name}} {{user.last_name}}</h3>
                <table>
                    <tr>
                        <th>Registered at:</th>
                        <td>{{user.created_at}}</td>
                    </tr>
                    <tr>
                        <th>User ID:</th>
                        <td>#{{user.id}}</td>
                    </tr>
                    <tr>
                        <th>Email address:</th>
                        <td>{{user.email}}</td>
                    </tr>
                    <tr>
                        <th>Description:</th>
                        <td>{{user.description}}</td>
                    </tr>
                </table>
            </div> <!-- end user info -->
            {% if user.id == request.session.user_id %}
            <div class='col-md-3'>
                <h3><a href="{% url 'dashboard:edit' user.id %}">Edit Profile</a></h3>
            </div>
            {% endif %}
        </div>
        <h4>New Message:</h4>
        <div class='row'>
            <div class='col-md-6'>
                <form action="{% url 'dashboard:new_message' user.id %}" method="post">
                    {% csrf_token %}
                    <textarea name='message' class='form-control' rows='3'></textarea>
                    <button type='submit' class='btn btn-primary btn-sm'>Add Message</button>
                </form>
            </div>
        </div> <!-- end Add Message form -->
        {% for message in messages%}
        <div class="message">
            <p class='bg-primary wall_content'><strong>{{message.messageuser.first_name}} wrote:</strong></p>
            <p class='wall_content'>{{message.message}}</p>
            {% for comment in comments %}
        	  	{% if message.id == comment.message.id %}
                    <p class='bg-success wall_content comment'><strong>{{comment.user.first_name}} wrote:</strong></p>
        	 		<p class='wall_content comment'>{{comment.comment}}</p>
        	 	{% endif %}
        	{% endfor %}
        	<div class='row'>
        	  	<div class='col-md-5 comment'>
        			<form action="{% url 'dashboard:new_comment' user.id message.id %}" method="post">
        				{% csrf_token %}
                        <textarea name='comment' class='form-control' rows='1'></textarea>
                        <button type='submit' class='btn btn-success btn-sm'>Add Comment</button>
        			</form>
        		</div>
        	</div>
        </div> <!-- end messages -->
        {% endfor %}
    </div>
</body>
</html>